class Location < ActiveRecord::Base
    has_many :users
    has_many :origins, foreign_key: "origin_id", class_name: "Post"
    has_many :destinations, foreign_key: "destination_id", class_name: "Post"

    def self.major_cities
        MAJOR_LOCATIONS
    end

    def full_name
        "#{city}, #{state}"
    end

    MAJOR_LOCATIONS = [
        'New York City, New York',
        'Los Angeles, California',
        'Chicago, Illinois',
        'Houston, Texas',
        'Phoenix, Arizona',
        'Philadelphia, Pennsylvania',
        'San Antonio, Texas',
        'San Diego, California',
        'Dallas, Texas',
        'San Jose, California',
        'Austin, Texas',
        'Jacksonville, Florida',
        'Fort Worth, Texas',
        'Columbus, Ohio',
        'Charlotte, North Carolina',
        'San Francisco, California',
        'Indianapolis, Indiana',
        'Seattle, Washington',
        'Denver, Colorado',
        'Washington, District of Columbia',
        'Boston, Massachusetts',
        'El Paso, Texas',
        'Nashville-Davidson, Tennessee',
        'Detroit, Michigan',
        'Oklahoma, Oklahoma',
        'Portland, Oregon',
        'Las Vegas, Nevada',
        'Memphis, Tennessee',
        'Louisville/Jefferson, Kentucky',
        'Baltimore, Maryland',
        'Milwaukee, Wisconsin',
        'Albuquerque, New Mexico',
        'Tucson, Arizona',
        'Fresno, California',
        'Mesa, Arizona',
        'Sacramento, California',
        'Atlanta, Georgia',
        'Kansas, Missouri',
        'Colorado Springs, Colorado',
        'Omaha, Nebraska',
        'Raleigh, North Carolina',
        'Miami, Florida',
        'Long Beach, California',
        'Virginia Beach, Virginia',
        'Oakland, California',
        'Minneapolis, Minnesota',
        'Tulsa, Oklahoma',
        'Tampa, Florida',
        'Arlington, Texas',
        'New Orleans, Louisiana',
        'Wichita, Kansas',
        'Bakersfield, California',
        'Cleveland, Ohio',
        'Aurora, Colorado',
        'Anaheim, California',
        'Urban Honolulu CDP, Hawaii',
        'Santa Ana, California',
        'Riverside, California',
        'Corpus Christi, Texas',
        'Lexington-Fayette urban, Kentucky',
        'Henderson, Nevada',
        'Stockton, California',
        'St. Paul, Minnesota',
        'Cincinnati, Ohio',
        'St. Louis, Missouri',
        'Pittsburgh, Pennsylvania',
        'Greensboro, North Carolina',
        'Lincoln, Nebraska',
        'Anchorage, Alaska',
        'Plano, Texas',
        'Orlando, Florida',
        'Irvine, California',
        'Newark, New Jersey',
        'Durham, North Carolina',
        'Chula Vista, California',
        'Toledo, Ohio',
        'Fort Wayne, Indiana',
        'St. Petersburg, Florida',
        'Laredo, Texas',
        'Jersey, New Jersey',
        'Chandler, Arizona',
        'Madison, Wisconsin',
        'Lubbock, Texas',
        'Scottsdale, Arizona',
        'Reno, Nevada',
        'Buffalo, New York',
        'Gilbert, Arizona',
        'Glendale, Arizona',
        'North Las Vegas, Nevada',
        'Winston-Salem, North Carolina',
        'Chesapeake, Virginia',
        'Norfolk, Virginia',
        'Fremont, California',
        'Garland, Texas',
        'Irving, Texas',
        'Hialeah, Florida',
        'Richmond, Virginia',
        'Boise, Idaho',
        'Spokane, Washington',
        'Baton Rouge, Louisiana',
        'Tacoma, Washington',
        'San Bernardino, California',
        'Modesto, California',
        'Fontana, California',
        'Des Moines, Iowa',
        'Moreno Valley, California',
        'Santa Clarita, California',
        'Fayetteville, North Carolina',
        'Birmingham, Alabama',
        'Oxnard, California',
        'Rochester, New York',
        'Port St. Lucie, Florida',
        'Grand Rapids, Michigan',
        'Huntsville, Alabama',
        'Salt Lake, Utah',
        'Frisco, Texas',
        'Yonkers, New York',
        'Amarillo, Texas',
        'Glendale, California',
        'Huntington Beach, California',
        'McKinney, Texas',
        'Montgomery, Alabama',
        'Augusta-Richmond, Georgia',
        'Aurora, Illinois',
        'Akron, Ohio',
        'Little Rock, Arkansas',
        'Tempe, Arizona',
        'Columbus, Georgia',
        'Overland Park, Kansas',
        'Grand Prairie, Texas',
        'Tallahassee, Florida',
        'Cape Coral, Florida',
        'Mobile, Alabama',
        'Knoxville, Tennessee',
        'Shreveport, Louisiana',
        'Worcester, Massachusetts',
        'Ontario, California',
        'Vancouver, Washington',
        'Sioux Falls, South Dakota',
        'Chattanooga, Tennessee',
        'Brownsville, Texas',
        'Fort Lauderdale, Florida',
        'Providence, Rhode Island',
        'Newport News, Virginia',
        'Rancho Cucamonga, California',
        'Santa Rosa, California',
        'Peoria, Arizona',
        'Oceanside, California',
        'Elk Grove, California',
        'Salem, Oregon',
        'Pembroke Pines, Florida',
        'Eugene, Oregon',
        'Garden Grove, California',
        'Cary, North Carolina',
        'Fort Collins, Colorado',
        'Corona, California',
        'Springfield, Missouri',
        'Jackson, Mississippi',
        'Alexandria, Virginia',
        'Hayward, California',
        'Clarksville, Tennessee',
        'Lakewood, Colorado',
        'Lancaster, California',
        'Salinas, California',
        'Palmdale, California',
        'Hollywood, Florida',
        'Springfield, Massachusetts',
        'Macon-Bibb, Georgia',
        'Kansas, Kansas',
        'Sunnyvale, California',
        'Pomona, California',
        'Killeen, Texas',
        'Escondido, California',
        'Pasadena, Texas',
        'Naperville, Illinois',
        'Bellevue, Washington',
        'Joliet, Illinois',
        'Murfreesboro, Tennessee',
        'Midland, Texas',
        'Rockford, Illinois',
        'Paterson, New Jersey',
        'Savannah, Georgia',
        'Bridgeport, Connecticut',
        'Torrance, California',
        'McAllen, Texas',
        'Syracuse, New York',
        'Surprise, Arizona',
        'Denton, Texas',
        'Roseville, California',
        'Thornton, Colorado',
        'Miramar, Florida',
        'Pasadena, California',
        'Mesquite, Texas',
        'Olathe, Kansas',
        'Dayton, Ohio',
        'Carrollton, Texas',
        'Waco, Texas',
        'Orange, California',
        'Fullerton, California',
        'Charleston, South Carolina',
        'West Valley, Utah',
        'Visalia, California',
        'Hampton, Virginia',
        'Gainesville, Florida',
        'Warren, Michigan',
        'Coral Springs, Florida',
        'Cedar Rapids, Iowa',
        'Round Rock, Texas',
        'Sterling Heights, Michigan',
        'Kent, Washington',
        'Columbia, South Carolina',
        'Santa Clara, California',
        'New Haven, Connecticut',
        'Stamford, Connecticut',
        'Concord, California',
        'Elizabeth, New Jersey',
        'Athens-Clarke, Georgia',
        'Thousand Oaks, California',
        'Lafayette, Louisiana',
        'Simi Valley, California',
        'Topeka, Kansas',
        'Norman, Oklahoma',
        'Fargo, North Dakota',
        'Wilmington, North Carolina',
        'Abilene, Texas',
        'Odessa, Texas',
        'Columbia, Missouri',
        'Pearland, Texas',
        'Victorville, California',
        'Hartford, Connecticut',
        'Vallejo, California',
        'Allen, Pennsylvania',
        'Berkeley, California',
        'Richardson, Texas',
        'Arvada, Colorado',
        'Ann Arbor, Michigan',
        'Rochester, Minnesota',
        'Cambridge, Massachusetts',
        'Sugar Land, Texas',
        'Lansing, Michigan',
        'Evansville, Indiana',
        'College Station, Texas',
        'Fairfield, California',
        'Clearwater, Florida',
        'Beaumont, Texas',
        'Independence, Missouri',
        'Provo, Utah',
        'West Jordan, Utah',
        'Murrieta, California',
        'Palm Bay, Florida',
        'El Monte, California',
        'Carlsbad, California',
        'North Charleston, South Carolina',
        'Temecula, California',
        'Clovis, California',
        'Springfield, Illinois',
        'Meridian, Idaho',
        'Westminster, Colorado',
        'Costa Mesa, California',
        'High Point, North Carolina',
        'Manchester, New Hampshire',
        'Pueblo, Colorado',
        'Lakeland, Florida',
        'Pompano Beach, Florida',
        'West Palm Beach, Florida',
        'Antioch, California',
        'Everett, Washington',
        'Downey, California',
        'Lowell, Massachusetts',
        'Centennial, Colorado',
        'Elgin, Illinois',
        'Richmond, California',
        'Peoria, Illinois',
        'Broken Arrow, Oklahoma',
        'Miami Gardens, Florida',
        'Billings, Montana',
        'Jurupa Valley, California',
        'Sandy Springs, Georgia',
        'Gresham, Oregon',
        'Lewisville, Texas',
        'Hillsboro, Oregon',
        'San Buenaventura, California',
        'Greeley, Colorado',
        'Inglewood, California',
        'Waterbury, Connecticut',
        'League, Texas',
        'Santa Maria, California',
        'Tyler, Texas',
        'Davie, Florida',
        'Daly, California',
        'Boulder, Colorado',
        'Allen, Texas',
        'West Covina, California',
        'Sparks, Nevada',
        'Wichita Falls, Texas',
        'Green Bay, Wisconsin',
        'San Mateo, California',
        'Norwalk, California',
        'Rialto, California',
        'Las Cruces, New Mexico',
        'Chico, California',
        'El Cajon, California',
        'Burbank, California',
        'South Bend, Indiana',
        'Renton, Washington',
        'Vista, California',
        'Davenport, Iowa',
        'Edinburg, Texas',
        'Tuscaloosa, Alabama',
        'Carmel, Indiana',
        'Spokane Valley, Washington',
        'San Angelo, Texas',
        'Vacaville, California',
        'Bend, Oregon',
        'Kenosha, Wisconsin',
        'Boca Raton, Florida',
        "Lee's Summit, Missouri",
        'Nampa, Idaho',
        'Rio Rancho, New Mexico',
        'South Fulton, Georgia',
        'Roanoke, Virginia',
        'Beaverton, Oregon',
        'Yuma, Arizona',
        'Lawrence, Kansas',
        'Orem, Utah',
        'Longmont, Colorado',
        'San Marcos, California',
        'Albany, New York',
        'Sandy, Utah',
        'Concord, North Carolina',
        'Federal Way, Washington',
        'Hesperia, California',
        'Brockton, Massachusetts',
        'Compton, California',
        'Flint, Michigan',
        'Erie, Pennsylvania',
        'New Bedford, Massachusetts',
        "Fishers, Indiana",
        'Sunrise, Florida',
        'Roswell, Georgia',
        'Menifee, California',
        'Tracy, California',
        'Plantation, Florida',
        'Quincy, Massachusetts',
        'Portsmouth, Virginia',
        'Mission Viejo, California',
        'Chino, California',
        'Lynn, Massachusetts',
        'Edmond, Oklahoma',
        'Dearborn, Michigan',
        'Livonia, Michigan',
        'Yakima, Washington',
        'South Gate, California',
        'Greenville, North Carolina',
        'Lawton, Oklahoma',
        'Kirkland, Washington',
        'Asheville, North Carolina',
        'Deltona, Florida',
        'Redding, California',
        'Bellingham, Washington',
        'Suffolk, Virginia',
        'Indio, California',
        'Mount Pleasant, South Carolina',
        'Carson, California',
        'Santa Barbara, California',
        'Conroe, Texas',
        'Westminster, California',
        'Santa Monica, California',
        'New Braunfels, Texas',
        'Livermore, California',
        'Palm Coast, Florida',
        'St. George, Utah',
        'Fall River, Massachusetts',
        'Nashua, New Hampshire',
        'Champaign, Illinois',
        'Miami Beach, Florida',
        'Norwalk, Connecticut',
        'San Leandro, California',
        "O'Fallon, Missouri",
        'Newton, Massachusetts',
        'Reading, Pennsylvania',
        'Avondale, Arizona',
        'Fort Smith, Arkansas',
        'Citrus Heights, California',
        'Ogden, Utah',
        'Fayetteville, Arkansas',
        'Fort Myers, Florida',
        'Goodyear, Arizona',
        'Bryan, Texas',
        'Waukegan, Illinois',
        'Hawthorne, California',
        'Redwood, California',
        'Hoover, Alabama',
        'Bloomington, Indiana',
        'Duluth, Minnesota',
        'Lake Forest, California',
        'Hemet, California',
        'Whittier, California',
        'Clifton, New Jersey',
        'Largo, Florida',
        'Bloomington, Minnesota',
        'Danbury, Connecticut',
        'Santa Fe, New Mexico',
        'Johns Creek, Georgia',
        'Newport Beach, California',
        'Kennewick, Washington',
        'Mission, Texas',
        'Milpitas, California',
        'Troy, Michigan',
        'Chino Hills, California',
        'Alhambra, California',
        'Merced, California',
        'Trenton, New Jersey',
        'Franklin, Tennessee',
        'Medford, Oregon',
        'Melbourne, Florida',
        'Manteca, California',
        'Mountain View, California',
        'Sioux, Iowa',
        'Lynchburg, Virginia',
        'Buena Park, California',
        'Pleasanton, California',
        'Longview, Texas',
        'Westland, Michigan',
        'Auburn, Washington',
        'Cranston, Rhode Island',
        'Somerville, Massachusetts',
        'Folsom, California',
        'Springdale, Arkansas',
        'Deerfield Beach, Florida',
        'Warwick, Rhode Island',
        'Cicero, Illinois',
        'Farmington Hills, Michigan',
        'Brooklyn Park, Minnesota',
        'Lawrence, Massachusetts',
        'Plymouth, Minnesota',
        'Buckeye, Arizona',
        'George, Texas',
        'Cedar Park, Texas',
        'Tustin, California',
        'Lakewood, California',
        'Perris, California',
        'Flower Mound, Texas',
        'Pharr, Texas',
        'Loveland, Colorado',
        'Boynton Beach, Florida',
        'New Rochelle, New York',
        'Temple, Texas',
        'Lake Charles, Louisiana',
        'Jonesboro, Arkansas',
        'Napa, California',
        'Parma, Ohio',
        'Layton, Utah',
        'Alameda, California',
        'Warner Robins, Georgia',
        'Rapid, South Dakota',
        'Bloomington, Illinois',
        'Gastonia, North Carolina',
        'Bay, Texas',
        'Upland, California',
        'Racine, Wisconsin',
        'Scranton, Pennsylvania',
        'South Jordan, Utah',
        'Bellflower, California',
        'Kalamazoo, Michigan',
        'San Ramon, California',
        'Bethlehem, Pennsylvania',
        'Wyoming, Michigan',
        'Hammond, Indiana',
        'Missoula, Montana',
        'Missouri, Texas',
        'Pasco, Washington',
        'Baldwin Park, California',
        'Iowa, Iowa',
        'Rancho Cordova, California',
        'Rock Hill, South Carolina',
        'Flagstaff, Arizona',
        'Gary, Indiana',
        'St. Joseph, Missouri',
        'Arlington Heights village, Illinois',
        'Bolingbrook village, Illinois',
        'Rochester Hills, Michigan',
        'Framingham, Massachusetts',
        'Union, California',
        'Appleton, Wisconsin',
        'Turlock, California',
        'Camden, New Jersey',
        'Bismarck, North Dakota',
        'Evanston, Illinois',
        'Apple Valley, California',
        'Schaumburg village, Illinois',
        'Woodbury, Minnesota',
        'Kissimmee, Florida',
        'Southfield, Michigan',
        'Maple Grove, Minnesota',
        'Pittsburg, California',
        'New Britain, Connecticut',
        'Jacksonville, North Carolina',
        'Mansfield, Texas',
        'Waukesha, Wisconsin',
        'Frederick, Maryland',
        'Albany, Georgia',
        'Pawtucket, Rhode Island',
        'Redmond, Washington',
        'Lauderhill, Florida',
        'Lafayette, Indiana',
        'Gulfport, Mississippi',
        'Redlands, California',
        'Weston, Florida',
        'St. Charles, Missouri',
        'Decatur, Illinois',
        'North Port, Florida',
        'North Richland Hills, Texas',
        'Greenville, South Carolina',
        'Bowling Green, Kentucky',
        'Broomfield, Colorado',
        'Canton, Ohio',
        'Marysville, Washington',
        'Walnut Creek, California',
        'Wilmington, Delaware',
        'Camarillo, California',
        'Lynwood, California',
        'Lehi, Utah',
        'Passaic, New Jersey',
        'Homestead, Florida',
        'Delray Beach, Florida',
        'Davis, California',
        'Lake Elsinore, California',
        'Daytona Beach, Florida',
        'Dothan, Alabama',
        'Rocklin, California',
        'Eau Claire, Wisconsin',
        'Rogers, Arkansas',
        'Castle Rock, Colorado',
        'St. Cloud, Minnesota',
        'Bossier, Louisiana',
        'Rockville, Maryland',
        'Muncie, Indiana',
        'Gaithersburg, Maryland',
        'Union, New Jersey',
        'West Des Moines, Iowa',
        'South San Francisco, California',
        'Yorba Linda, California',
        'Conway, Arkansas',
        'Lodi, California',
        'Palatine village, Illinois',
        'Ankeny, Iowa',
        'Mount Vernon, New York',
        'Rowlett, Texas',
        'Waterloo, Iowa',
        'Lakeville, Minnesota',
        'Alpharetta, Georgia',
        'Jackson, Tennessee',
        'Yuba, California',
        'Oshkosh, Wisconsin',
        'Victoria, Texas',
        'Johnson, Tennessee',
        'Redondo Beach, California',
        'Tamarac, Florida',
        'Laguna Niguel, California',
        'Eagan, Minnesota',
        'Kenner, Louisiana',
        'Auburn, Alabama',
        'Ames, Iowa',
        'Portland, Maine',
        'North Little Rock, Arkansas',
        'Sammamish, Washington',
        'Madera, California',
        'Shawnee, Kansas',
        'Jupiter, Florida',
        'Doral, Florida',
        'Blaine, Minnesota',
        'Tulare, California',
        'Youngs, Ohio',
        'Wellington village, Florida',
        'Pflugerville, Texas',
        'Palo Alto, California',
        'Schenectady, New York',
        'Harlingen, Texas',
        'Bayonne, New Jersey',
        'Eden Prairie, Minnesota',
        'Port Orange, Florida',
        'Dublin, California',
        'San Marcos, Texas',
        'Noblesville, Indiana',
        'Santa Cruz, California',
        'Janesville, Wisconsin',
        'San Clemente, California',
        'Brentwood, California',
        'East Orange, New Jersey',
        'Cheyenne, Wyoming',
        'Eastvale, California',
        'Chapel Hill, North Carolina',
        'Haverhill, Massachusetts',
        'Lorain, Ohio',
        'Grand Junction, Colorado',
        'Springfield, Oregon',
        'Coon Rapids, Minnesota',
        'Idaho Falls, Idaho',
        'North Miami, Florida',
        'Encinitas, California',
        'Skokie village, Illinois',
        'Leander, Texas',
        'Waltham, Massachusetts',
        'Council Bluffs, Iowa',
        'Hamilton, Ohio',
        'Moore, Oklahoma',
        'Pico Rivera, California',
        'Montebello, California',
        'Millcreek, Utah',
        'Sanford, Florida',
        'National, California',
        'Burnsville, Minnesota',
        'Coconut Creek, Florida',
        'Lakewood, Washington',
        'Taylor, Michigan',
        'Novi, Michigan',
        'Marietta, Georgia',
        'Ocala, Florida',
        'Terre Haute, Indiana',
        'Woodland, California',
        'Petaluma, California',
        'La Habra, California',
        'Malden, Massachusetts',
        'Commerce, Colorado',
        'Owensboro, Kentucky',
        'Bristol, Connecticut',
        'West Allis, Wisconsin',
        'Taylorsville, Utah',
        'Utica, New York',
        'Monterey Park, California',
        'Bonita Springs, Florida',
        'Porterville, California',
        'Greenwood, Indiana',
        'Bartlett, Tennessee',
        'Bradenton, Florida',
        'Vineland, New Jersey',
        'Pontiac, Michigan',
        'Meriden, Connecticut',
        'Gardena, California',
        'Apex, North Carolina',
        'Royal Oak, Michigan',
        'Cupertino, California',
        'Lancaster, Pennsylvania',
        'La Mesa, California',
        'Gilroy, California',
        'St. Clair Shores, Michigan',
        'Des Plaines, Illinois',
        'Springfield, Ohio',
        'Corvallis, Oregon',
        'Margate, Florida',
        'Bowie, Maryland',
        'Casa Grande, Arizona',
        'Caldwell, Idaho',
        'San Rafael, California',
        'Great Falls, Montana',
        'Sarasota, Florida',
        'Richland, Washington',
        'St. Peters, Missouri',
        'Hendersonville, Tennessee',
        'White Plains, New York',
        'Huntersville, North Carolina',
        'Santee, California',
        'Kokomo, Indiana',
        'Arcadia, California',
        'Casper, Wyoming',
        'Dubuque, Iowa',
        'Orland Park village, Illinois',
        'Weymouth, Massachusetts',
        'Parker, Colorado',
        'Palm Beach Gardens, Florida',
        'Hanford, California',
        'Huntington Park, California',
        'Taunton, Massachusetts',
        'Midwest, Oklahoma',
        'Medford, Massachusetts',
        'Euless, Texas',
        'Shoreline, Washington',
        'Smyrna, Georgia',
        'Pocatello, Idaho',
        'Valdosta, Georgia',
        'Carson, Nevada',
        'Lake Havasu, Arizona',
        'Grand Forks, North Dakota',
        'Blue Springs, Missouri',
        'Southaven, Mississippi',
        'Tinley Park village, Illinois',
        'Diamond Bar, California',
        'New Brunswick, New Jersey',
        'Lenexa, Kansas',
        'Brookhaven, Georgia',
        'Novato, California',
        'Tigard, Oregon',
        'Highland, California',
        'Fountain Valley, California',
        'Dearborn Heights, Michigan',
        'Albany, Oregon',
        'Grapevine, Texas',
        'Apple Valley, Minnesota',
        'Chicopee, Massachusetts',
        'Hempstead village, New York',
        'Oak Lawn village, Illinois',
        'Cathedral, California',
        'Bentonville, Arkansas',
        'Stonecrest, Georgia',
        'Kettering, Ohio',
        'Colton, California',
        'Anderson, Indiana',
        'West Haven, Connecticut',
        'Burlington, North Carolina',
        'Manhattan, Kansas',
        'St. Cloud, Florida',
        'Normal, Illinois',
        'Decatur, Alabama',
        'Berwyn, Illinois',
        'Port Arthur, Texas',
        'Kingsport, Tennessee',
        'Minnetonka, Minnesota',
        'Rosemead, California',
        'Paramount, California',
        'Rocky Mount, North Carolina',
        'Yucaipa, California',
        'Watsonville, California',
        'Elyria, Ohio',
        'Leesburg, Virginia',
        'Mount Prospect village, Illinois',
        'Pinellas Park, Florida',
        'Delano, California',
        'Bellevue, Nebraska',
        'West Sacramento, California',
        'Apopka, Florida',
        'Palm Desert, California',
        'Milford, Connecticut',
        'Little Elm, Texas',
        'Revere, Massachusetts',
        'Peabody, Massachusetts',
        'Wylie, Texas',
        'Harrisonburg, Virginia',
        'DeSoto, Texas',
        'Pensacola, Florida',
        'Olympia, Washington',
        'Edina, Minnesota',
        'Wheaton, Illinois',
        'West New York, New Jersey',
        'Hoboken, New Jersey',
        'Lacey, Washington',
        'Summerville, South Carolina',
        "Coeur dAlene, Idaho",
        'Oak Park village, Illinois',
        'Elkhart, Indiana',
        'Maricopa, Arizona',
        'Kentwood, Michigan',
        'Madison, Alabama',
        'Smyrna, Tennessee',
        'Glendora, California',
        'Logan, Utah',
        'Burien, Washington',
        'Perth Amboy, New Jersey',
        'Herriman, Utah',
        'Grand Island, Nebraska',
        'Placentia, California',
        'La Crosse, Wisconsin',
        'Battle Creek, Michigan',
        'Beaumont, California',
        'Collierville, Tennessee',
        'West Lafayette, Indiana',
        'Florissant, Missouri',
        'Hoffman Estates village, Illinois',
        'Joplin, Missouri',
        'Queen Creek, Arizona',
        'Aliso Viejo, California',
        'Kannapolis, North Carolina',
        'Methuen, Massachusetts',
        'Galveston, Texas',
        'Mishawaka, Indiana',
        'Plainfield, New Jersey',
        'Newark, Ohio',
        'Stillwater, Oklahoma',
        'Twin Falls, Idaho',
        'Texas, Texas',
        'Cerritos, California',
        'Coral Gables, Florida',
        'Enid, Oklahoma',
        'Lakewood, Ohio',
        'Troy, New York',
        'Saginaw, Michigan',
        'Niagara Falls, New York',
        'Charleston, West Virginia'
    ]

end